FROM rocker/shiny
# https://registry.hub.docker.com/u/rocker/shiny/dockerfile/

# RUN R -e "install.packages(c('caret', 'e1071','rpart','dplyr'))"
RUN R -e 'install.packages(c("dplyr","leaflet","DT"))'
#RUN install2.r --error \
#    Rccp \
#    dplyr \
#    ggplot2 \
#    tidyr \
